//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bike
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bike()
        {
            this.rentDetails = new HashSet<rentDetail>();
        }
    
        public int id_bike { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string describe { get; set; }
        public string mass { get; set; }
        public string volumn { get; set; }
        public string size { get; set; }
        public string consume { get; set; }
        public string status { get; set; }
    
        public virtual type types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentDetail> rentDetails { get; set; }
    }
}
