//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class menu
    {
        public int id { get; set; }
        [DisplayName("Tiêu đề")]
        public string title { get; set; }
        [DisplayName("Đường dẫn")]

        public string link { get; set; }
        [DisplayName("Hiển thị")]

        public Nullable<bool> IsActive { get; set; }
        [DisplayName("Thứ tự")]

        public Nullable<int> order { get; set; }
    }
}
