//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeMay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RENT_MOTOREntities : DbContext
    {
        public RENT_MOTOREntities()
            : base("name=RENT_MOTOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bike> bikes { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<mail> mails { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<rate> rates { get; set; }
        public virtual DbSet<rent> rents { get; set; }
        public virtual DbSet<rentDetail> rentDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
