//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate
    {
        public int id { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public string content { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string image { get; set; }
    }
}
